### ISSUE TITLE
negative interaction with audio_session

### ISSUE THREAD

**Issue by lukepighetti** [alnitak/flutter_soloud#104]
https://github.com/ryanheise/audio_session/issues/138

**Comment by alnitak** [comment]
Hey @lukepighetti,

I read **ryanheise** reply. Unfortunately, I don't have a Mac to try. What I can say is that `loadAsset()` does nothing else than read using `rootbundle` or give the file directly to the native if it is already cached.

In the `flutter_soloud` version you are using, an `Isolate` is used to perform the native call. This could be the only reason that come to my mind that could cause something out of the ordinary. The `main` branch got rid of the Isolate and maybe worth to try it. It's not yet been published, so you should link this repo in your `pubspec.yaml` like:
```
  flutter_soloud:
    git:
      url: https://github.com/alnitak/flutter_soloud.git
      # Add this if you want to try with the incoming web support.
      # path: web
```
Also, have you tried to load the asset before calling `_session.setActive(true)`?
